from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ba70c215ce20'
down_revision = '602242989cdd'
branch_labels = None
depends_on = None
def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint('uq_users_username', 'users', ['username'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
